image: docker:stable

variables:
    #  DOCKER_HOST: tcp://docker:2375/
    #  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CONTAINER_IMAGE:latest

  #services:
  #  - docker:dind

stages:
  - build
  - test
    #  - release
    #  - deploy

before_script:
    #  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWD
  - echo $CONTAINER_IMAGE

build:docker:
  stage: build
  script:
    - echo "$DOCKER_HUB_PASSWD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker image build -t $CONTAINER_TEST_IMAGE .
    - docker image push $CONTAINER_TEST_IMAGE
  only:
    - dev
      #  tags:
      #    - docker
      #    - dind

      #test:docker:
      #  stage: test
      #  script:
      #    - docker pull $CONTAINER_TEST_IMAGE
      #    - docker container run --rm $CONTAINER_TEST_IMAGE npm test
      #  tags:
      #    - docker
      #    - dind

